apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: contour
    helmChart:
      name: contour
      version: "7.10.2"
      repository:
        url: https://charts.bitnami.com/bitnami
